export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

import 'styles/globals.css';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="h-screen flex">
        <div className="xl:w-full sm:none bg-secondary flex items-center justify-center p-16">
          {children}
        </div>
      </body>
    </html>
  );
}
