export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

import 'styles/globals.css';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="h-screen flex">
        <div className="xl:w-1/2 sm:w-full bg-teal-400 flex items-center justify-center p-16" />

        {children}

        <div className="xl:w-1/2 sm:none bg-neutral-900 flex items-center justify-center p-16" />
      </body>
    </html>
  );
}
