'use client';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js'
};

import 'styles/globals.css';
import { MainContainer } from './styles';

export default function RootLayout({
  children
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt-BR">
      <body className="h-screen flex">
        <MainContainer>{children}</MainContainer>
      </body>
    </html>
  );
}
